services:
  mysql:
    image: mysql:8
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moneymgmt
    ports:
      - "3306:3306"
    networks:
      - money-mgmt
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  money-mgmt:
    external: true

volumes:
  mysql_data:
